version: "3.8"

services:
    redis:
        container_name: redis
        image: redis:6.0
        mem_limit: 16m
        mem_reservation: 8m
        # cpus: 0.1
        ports:
            - 6379:6379
    bommgate:
        container_name: boomgate-container
        image: berodimas/boomgate-demo:1.0
        mem_limit: 64m
        mem_reservation: 32m
        cpus: 0.15
        environment: 
            - DISPLAY=172.31.144.1:0.0
        
        