# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mockup4.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import pyqtSlot, QDate, QTimer, QTime, Qt, QObject, QThread, pyqtSignal, QThreadPool, QRunnable, QTranslator
from PyQt5.QtWidgets import QLabel, QPushButton, QAction, QApplication, QLineEdit, QMainWindow, QMenu, QWidgetAction, QMessageBox
from PyQt5.QtGui import QImage, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self._mainwindow = MainWindow
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #353942;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_bot_right = QtWidgets.QVBoxLayout()
        self.layout_bot_right.setObjectName("layout_bot_right")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_bot_right.addItem(spacerItem)
        self.label_top = QtWidgets.QLabel(self.centralwidget)
        self.label_top.setMinimumSize(QtCore.QSize(380, 0))
        self.label_top.setStyleSheet("font-family: Open Sans;\n"
"font-size: 24px;\n"
"color: rgb(255, 255, 255);")
        self.label_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_top.setObjectName("label_top")
        self.layout_bot_right.addWidget(self.label_top)
        self.label_bot = QtWidgets.QLabel(self.centralwidget)
        self.label_bot.setStyleSheet("font-family: Open Sans;\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255);")
        self.label_bot.setText("")
        self.label_bot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bot.setObjectName("label_bot")
        self.layout_bot_right.addWidget(self.label_bot)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_bot_right.addItem(spacerItem1)
        self.gridLayout.addLayout(self.layout_bot_right, 2, 1, 1, 1)
        self.layout_mid_right = QtWidgets.QVBoxLayout()
        self.layout_mid_right.setObjectName("layout_mid_right")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        # self.label_image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.layout_mid_right.addWidget(self.label_image)
        self.gridLayout.addLayout(self.layout_mid_right, 1, 1, 1, 1)
        self.layout_left = QtWidgets.QVBoxLayout()
        self.layout_left.setSpacing(10)
        self.layout_left.setObjectName("layout_left")
        self.container_camera_top = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container_camera_top.sizePolicy().hasHeightForWidth())
        self.container_camera_top.setSizePolicy(sizePolicy)
        self.container_camera_top.setStyleSheet("border: 1px solid black")
        self.container_camera_top.setObjectName("container_camera_top")
        self.layout_left.addWidget(self.container_camera_top)
        self.gridLayout.addLayout(self.layout_left, 0, 0, 3, 1)
        self.layout_top_right = QtWidgets.QVBoxLayout()
        self.layout_top_right.setObjectName("layout_top_right")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setStyleSheet("font: bold 14pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.layout_top_right.addWidget(self.label_date)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_top_right.addItem(spacerItem2)
        self.gridLayout.addLayout(self.layout_top_right, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qlue Boomgate"))
